---
- name: Activity-Playbook
  hosts: webservers
  become: true
  tasks:
  - name: uninstall apache2
    apt:
     name: apache2
     state: absent

  - name: docker.io
    apt:
     name: docker.io
     force_apt_get: yes
     state: present
     update_cache: yes

  - name: Install pip3
    apt:
     force_apt_get: yes
     name: python3-pip
     state: present

  - name: Install Docker python module
    pip:
     name: docker
